"""
Excel Template Generator for Rhino Data Visualization Tool
Creates the MetadataTemplate.xlsx file with proper table structure
"""

try:
    from openpyxl import Workbook
    from openpyxl.worksheet.table import Table, TableStyleInfo
    from openpyxl.styles import Font, PatternFill
except ImportError:
    print("ERROR: openpyxl not installed.")
    print("Install with: pip install openpyxl")
    exit()

import os

# Create workbook
wb = Workbook()
ws = wb.active
ws.title = "Configuration"

# Header styling
header_font = Font(bold=True, size=12)
header_fill = PatternFill(start_color="366092", end_color="366092", fill_type="solid")

# Create Key Definitions section
ws['A1'] = 'Key Definitions'
ws['A1'].font = Font(bold=True, size=14)

# Key Definitions table headers
ws['A3'] = 'Key Name'
ws['B3'] = 'Default Value'
ws['A3'].font = header_font
ws['B3'].font = header_font
ws['A3'].fill = header_fill
ws['B3'].fill = header_fill

# Example keys
example_keys = [
    ['Building Year', ''],
    ['Latest Renovation', ''],
    ['Condition', 'Good'],
    ['Department', ''],
    ['Refurbish or Demolish', '']
]

for idx, (key, value) in enumerate(example_keys, start=4):
    ws[f'A{idx}'] = key
    ws[f'B{idx}'] = value

# Create table for Key Definitions
key_table = Table(displayName='_KeyDefinitions', ref=f'A3:B{3 + len(example_keys)}')
style = TableStyleInfo(
    name="TableStyleMedium9",
    showFirstColumn=False,
    showLastColumn=False,
    showRowStripes=True,
    showColumnStripes=False
)
key_table.tableStyleInfo = style
ws.add_table(key_table)

# Adjust column widths
ws.column_dimensions['A'].width = 25
ws.column_dimensions['B'].width = 20

# Add instructions
ws['A12'] = 'Instructions:'
ws['A12'].font = Font(bold=True, size=12)
ws['A13'] = '1. Define your metadata keys in the table above'
ws['A14'] = '2. Run Script 01 to apply keys to selected objects in Rhino'
ws['A15'] = '3. Fill in values for your objects in Rhino (use SetUserText command)'
ws['A16'] = '4. Run Script 02 to extract unique values and generate color mapping tables'
ws['A17'] = '5. Fill in HEX colors (or RGB values) for each unique value'
ws['A18'] = '6. Run Script 03 to visualize objects by their metadata values'

# Note about color maps
ws['A20'] = 'Note: Color mapping tables will be auto-generated by Script 02 in this same sheet'
ws['A20'].font = Font(italic=True, color="666666")

# Save the file
script_dir = os.path.dirname(os.path.abspath(__file__))
output_path = os.path.join(script_dir, 'MetadataTemplate.xlsx')
wb.save(output_path)
print(f"Excel template created successfully: {output_path}")
print("\nThe template includes:")
print("- _KeyDefinitions table with example keys")
print("- Instructions for the workflow")
print("- Proper formatting and structure")
